/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import org.example.db.HibernateUtil;
import org.example.model.Album;
import org.example.model.Artist;
import org.example.model.Song;
import org.json.JSONArray;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());
        Path f = Paths.get("songs.json");
        String jsonInput = Files.readString(f);
        var jsonArray = new JSONArray(jsonInput);
        var firstSong = jsonArray.getJSONObject(0);
        System.out.println(firstSong);
        Song chaiyya = new Song();
        chaiyya.setName(firstSong.getString("name"));
        Album dilSe = new Album();
        var albumJSONObject = firstSong.getJSONObject("album");
        dilSe.setName(albumJSONObject.getString("name"));
        dilSe.setYearOfRelease(albumJSONObject.getString("year_of_release"));
        dilSe.setLanguage(albumJSONObject.getString("language"));
        Artist rahman = new Artist();
        var musicDirectorJSONObject = albumJSONObject.getJSONObject("music_director");
        rahman.setName(musicDirectorJSONObject.getString("name"));
        rahman.setYearOfBirth(musicDirectorJSONObject.getString("year_of_birth"));
        rahman.setGender(musicDirectorJSONObject.getString("gender"));
        dilSe.setMusicDirector(rahman);
        chaiyya.setAlbum(dilSe);

        var artistArray = firstSong.getJSONArray("artists");
        for (int i = 0; i < artistArray.length(); i++) {
            Artist artist = new Artist();
            var artistJsonObject = artistArray.getJSONObject(i);
            artist.setName(artistJsonObject.getString("name"));
            artist.setYearOfBirth(artistJsonObject.getString("year_of_birth"));
            artist.setGender(artistJsonObject.getString("gender"));
            chaiyya.addArtist(artist);
        }
        chaiyya.setLanguage(firstSong.getString("language"));
        chaiyya.setGenre(firstSong.getString("genre"));

        var sessionFactory = HibernateUtil.getSessionFactory();
        // sessionFactory.inTransaction(session -> {
        //     session.persist(chaiyya);
        // });
        var session = sessionFactory.openSession();
        var dilSeFromDB = session.find(Album.class, 1);
        session.close();
        // var anotherSession = sessionFactory.openSession();
        // var txn = anotherSession.beginTransaction();
        // anotherSession.merge(dilSeFromDB);
        // var arRahmanFromDB = dilSeFromDB.getMusicDirector();
        //     var songToPersist = new Song();
        //     songToPersist.setName("Dil Se Re");
        //     songToPersist.setAlbum(dilSeFromDB);
        //     songToPersist.addArtist(arRahmanFromDB);
        //     songToPersist.setLanguage("hindi");
        //     songToPersist.setGenre("romance");
        // anotherSession.persist(songToPersist);
        // txn.commit();
        // anotherSession.close();
        System.out.println(dilSeFromDB.getLanguage());
        sessionFactory.close();
    }
}
